[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install"
]

[phases.build]
cmds = ["echo build complete"]

[phases.start]
cmd = "npm start"
